# Generated by Django 4.2.4 on 2024-11-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationrecord',
            old_name='pet',
            new_name='patient',
        ),
    ]
